In [2]:
import pandas as pd
import numpy as np

In [5]:
#cargar los data frame de datos y de entrenamientos
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [8]:
print(train.isnull().sum())
print('')
print(test.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


# Limpieza

In [13]:
train = pd.get_dummies(train, columns = ["Sex"], drop_first = True)
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                               Heikkinen, Miss. Laina  26.0      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                             Allen, Mr. William Henry  35.0      0      0   
..                                                 ...   ...    ...    ...   
886                              Montvila, Rev. Juozas  27.0      0      0   
887                       Graham, Miss. Margaret Edith  19.0      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   NaN      1      2   
889                              Behr, Mr. Karl Howell  26.0      0      0   
890                                Dooley, Mr. Patrick  32.0      0      0   

               Ticket     Fare Cabin Embarked  Sex_male  
0           A/5 21171   7.2500   NaN        S         1  
1            PC 17599  71.2833   C85        C         0  
2    STON/O2. 3101282   7.9250   NaN        S         0  
3              113803  53.1000  C123        S         0  
4              373450   8.0500   NaN        S         1  
..                ...      ...   ...      ...       ...  
886            211536  13.0000   NaN        S         1  
887            112053  30.0000   B42        S         0  
888        W./C. 6607  23.4500   NaN        S         0  
889            111369  30.0000  C148        C         1  
890            370376   7.7500   NaN        Q         1  

[891 rows x 12 columns]

In [14]:
test = pd.get_dummies(test, columns = ["Sex"], drop_first = True)
test

PassengerId  Pclass                                          Name   Age  \
0            892       3                              Kelly, Mr. James  34.5   
1            893       3              Wilkes, Mrs. James (Ellen Needs)  47.0   
2            894       2                     Myles, Mr. Thomas Francis  62.0   
3            895       3                              Wirz, Mr. Albert  27.0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0   
..           ...     ...                                           ...   ...   
413         1305       3                            Spector, Mr. Woolf   NaN   
414         1306       1                  Oliva y Ocana, Dona. Fermina  39.0   
415         1307       3                  Saether, Mr. Simon Sivertsen  38.5   
416         1308       3                           Ware, Mr. Frederick   NaN   
417         1309       3                      Peter, Master. Michael J   NaN   

     SibSp  Parch              Ticket      Fare Cabin Embarked  Sex_male  
0        0      0              330911    7.8292   NaN        Q         1  
1        1      0              363272    7.0000   NaN        S         0  
2        0      0              240276    9.6875   NaN        Q         1  
3        0      0              315154    8.6625   NaN        S         1  
4        1      1             3101298   12.2875   NaN        S         0  
..     ...    ...                 ...       ...   ...      ...       ...  
413      0      0           A.5. 3236    8.0500   NaN        S         1  
414      0      0            PC 17758  108.9000  C105        C         0  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S         1  
416      0      0              359309    8.0500   NaN        S         1  
417      1      1                2668   22.3583   NaN        C         1  

[418 rows x 11 columns]

In [27]:
train.rename(columns = {'Sex_male':'Sex'}, inplace=True)
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                               Heikkinen, Miss. Laina  26.0      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                             Allen, Mr. William Henry  35.0      0      0   
..                                                 ...   ...    ...    ...   
886                              Montvila, Rev. Juozas  27.0      0      0   
887                       Graham, Miss. Margaret Edith  19.0      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   NaN      1      2   
889                              Behr, Mr. Karl Howell  26.0      0      0   
890                                Dooley, Mr. Patrick  32.0      0      0   

               Ticket     Fare Cabin  Embarked  Sex  
0           A/5 21171   7.2500   NaN       2.0    1  
1            PC 17599  71.2833   C85       3.0    0  
2    STON/O2. 3101282   7.9250   NaN       2.0    0  
3              113803  53.1000  C123       2.0    0  
4              373450   8.0500   NaN       2.0    1  
..                ...      ...   ...       ...  ...  
886            211536  13.0000   NaN       2.0    1  
887            112053  30.0000   B42       2.0    0  
888        W./C. 6607  23.4500   NaN       2.0    0  
889            111369  30.0000  C148       3.0    1  
890            370376   7.7500   NaN       1.0    1  

[891 rows x 12 columns]

In [26]:
train.Embarked.replace(['Q','S','C'], [1,2,3], inplace = True)
train

TypeError: Cannot compare types 'ndarray(dtype=float64)' and 'str'

In [25]:
test.Embarked.replace(['Q','S','C'], [1,2,3], inplace = True)

In [28]:
test.rename(columns = {'Sex_male':'Sex'}, inplace=True)
test

PassengerId  Pclass                                          Name   Age  \
0            892       3                              Kelly, Mr. James  34.5   
1            893       3              Wilkes, Mrs. James (Ellen Needs)  47.0   
2            894       2                     Myles, Mr. Thomas Francis  62.0   
3            895       3                              Wirz, Mr. Albert  27.0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0   
..           ...     ...                                           ...   ...   
413         1305       3                            Spector, Mr. Woolf   NaN   
414         1306       1                  Oliva y Ocana, Dona. Fermina  39.0   
415         1307       3                  Saether, Mr. Simon Sivertsen  38.5   
416         1308       3                           Ware, Mr. Frederick   NaN   
417         1309       3                      Peter, Master. Michael J   NaN   

     SibSp  Parch              Ticket      Fare Cabin  Embarked  Sex  
0        0      0              330911    7.8292   NaN         1    1  
1        1      0              363272    7.0000   NaN         2    0  
2        0      0              240276    9.6875   NaN         1    1  
3        0      0              315154    8.6625   NaN         2    1  
4        1      1             3101298   12.2875   NaN         2    0  
..     ...    ...                 ...       ...   ...       ...  ...  
413      0      0           A.5. 3236    8.0500   NaN         2    1  
414      0      0            PC 17758  108.9000  C105         3    0  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN         2    1  
416      0      0              359309    8.0500   NaN         2    1  
417      1      1                2668   22.3583   NaN         3    1  

[418 rows x 11 columns]

In [29]:
print(test.Age.mean())
print(train.Age.mean())

30.272590361445783
29.69911764705882


In [30]:
train.Age.fillna(train.Age.mean(), inplace=True)
test.Age.fillna(test.Age.mean(), inplace=True)

In [31]:
print(train.isnull().sum())
print('')
print(test.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Sex              0
dtype: int64

PassengerId      0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Sex              0
dtype: int64


In [33]:
train.drop(['Cabin','PassengerId','Name','Ticket'],1,inplace=True)

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Sex         0
dtype: int64

PassengerId      0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Sex              0
dtype: int64


In [34]:
test.drop(['Cabin','Name','Ticket'],1,inplace=True)
print(train.isnull().sum())
print('')
print(test.isnull().sum())

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Sex         0
dtype: int64

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
Sex            0
dtype: int64


In [35]:
rango = [0,8,15,18,25,40,60,100]
etiqueta = ['1','2','3','4','5','6','7']
train.Age = pd.cut(train.Age, rango, labels = etiqueta)
train

Survived  Pclass Age  SibSp  Parch     Fare  Embarked  Sex
0           0       3   4      1      0   7.2500       2.0    1
1           1       1   5      1      0  71.2833       3.0    0
2           1       3   5      0      0   7.9250       2.0    0
3           1       1   5      1      0  53.1000       2.0    0
4           0       3   5      0      0   8.0500       2.0    1
..        ...     ...  ..    ...    ...      ...       ...  ...
886         0       2   5      0      0  13.0000       2.0    1
887         1       1   4      0      0  30.0000       2.0    0
888         0       3   5      1      2  23.4500       2.0    0
889         1       1   5      0      0  30.0000       3.0    1
890         0       3   5      0      0   7.7500       1.0    1

[891 rows x 8 columns]

In [36]:
rango = [0,8,15,18,25,40,60,100]
etiqueta = ['1','2','3','4','5','6','7']
test.Age = pd.cut(test.Age, rango, labels = etiqueta)
test

PassengerId  Pclass Age  SibSp  Parch      Fare  Embarked  Sex
0            892       3   5      0      0    7.8292         1    1
1            893       3   6      1      0    7.0000         2    0
2            894       2   7      0      0    9.6875         1    1
3            895       3   5      0      0    8.6625         2    1
4            896       3   4      1      1   12.2875         2    0
..           ...     ...  ..    ...    ...       ...       ...  ...
413         1305       3   5      0      0    8.0500         2    1
414         1306       1   5      0      0  108.9000         3    0
415         1307       3   5      0      0    7.2500         2    1
416         1308       3   5      0      0    8.0500         2    1
417         1309       3   5      1      1   22.3583         3    1

[418 rows x 8 columns]

In [37]:
print(train.isnull().sum())
print('')
print(test.isnull().sum())

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Sex         0
dtype: int64

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
Sex            0
dtype: int64


In [38]:
train.dropna(axis=0, how='any', inplace = True)
print(train.isnull().sum())

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Sex         0
dtype: int64


In [39]:
test.dropna(axis=0, how='any', inplace = True)
print(test.isnull().sum())

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Sex            0
dtype: int64


# aplicar modelos de aprendizaje supervisado

In [41]:
X = np.array(train.drop(['Survived'],axis=1))

In [42]:
X

array([[3, '4', 1, ..., 7.25, 2.0, 1],
       [1, '5', 1, ..., 71.2833, 3.0, 0],
       [3, '5', 0, ..., 7.925, 2.0, 0],
       ...,
       [3, '5', 1, ..., 23.45, 2.0, 0],
       [1, '5', 0, ..., 30.0, 3.0, 1],
       [3, '5', 0, ..., 7.75, 1.0, 1]], dtype=object)

In [44]:
y = np.array(train.Survived)
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [45]:
from sklearn.model_selection import *
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)


In [54]:
from sklearn.linear_model import *
regresion_logistica = LogisticRegression(solver='liblinear')
regresion_logistica.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
pred = regresion_logistica.predict(X_test)
pred

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1], dtype=int64)

In [57]:
y_test

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1], dtype=int64)

In [67]:
print(regresion_logistica.score(X_train, y_train)*100)

81.0126582278481


In [68]:
# soporte de vectores

In [71]:
from sklearn.svm import *

soporte_vectores = SVC()
soporte_vectores.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [72]:
prediccion = soporte_vectores.predict(X_test)
prediccion

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0], dtype=int64)

In [75]:
print(soporte_vectores.score(X_train, y_train)*100)

85.93530239099859


In [74]:
# vecinos mas cercanos

In [90]:
from sklearn.neighbors import *
knc = KNeighborsClassifier(n_neighbors=2)

knc.fit(X_train, y_train)

pred = knc.predict(X_test)
pred

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [91]:
print(knc.score(X_train, y_train)*100)

86.21659634317862


In [ ]:
# ejecucion

In [94]:
identificador = test.PassengerId
identificador

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 417, dtype: int64

In [92]:
#regresion logistica

In [95]:
#test_reg_log = LogisticRegression(solver='liblinear')
#test_reg_log.fit(X_train, y_train)
#pred = test_reg_log.predict(X_test)
#pred

test_reg_log = reg_log.predict(test.drop(['PassengerId'],axis=1))

NameError: name 'reg_log' is not defined